---
#If commit was done to any branch, which name starts with “feature/” - build image, tag it with short hash of commit
# and latest tags, and push these images to gitlab container registry of this repository
build_image_from_feature_branch:
  stage: build
  tags:
    - docker-shared
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feature*/'
  script:
    - docker build -t "${CI_COMMIT_SHORT_SHA}:latest" . --label "maintainer=$GITLAB_USER_NAME"
    - docker image ls | grep "${CI_COMMIT_SHORT_SHA}:latest"
  after_script:
    - docker image rm "${CI_COMMIT_SHORT_SHA}:latest"

# If commit was done to master branch through merge request -
# build image, tag it with pipeline id and push image to gitlab container registry
build_image_from_merge_request_to_main:
  stage: build
  tags:
    - docker-shared
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  script:
    - docker build -t "$CI_PIPELINE_ID" . --label "maintainer=$GITLAB_USER_NAME"
    - docker image ls | grep "$CI_PIPELINE_ID"
  after_script:
    - docker image rm "$CI_PIPELINE_ID"

# If someone tag master branch -
# build image and tag it with branch’s tag and push it to gitlab container registry
build_image_if_tagged_main:
  stage: build
  tags:
    - docker-shared
  only:
    - '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - tags
  script:
    - docker build -t "$CI_COMMIT_TAG" . --label "maintainer=$GITLAB_USER_NAME"
    - docker image ls | grep "$CI_COMMIT_TAG"
  after_script:
    - docker image rm "$CI_COMMIT_TAG"
