stages:
  - build
  - test
  - deploy

build:
  tags:
    - docker-shared
  stage: build
  script: echo "$CI_JOB_NAME"

unit:
  tags:
    - docker-shared
  stage: test
  needs:
    - build
  script: echo "$CI_JOB_NAME"

lint:
  tags:
    - docker-shared
  stage: test
  script: echo "$CI_JOB_NAME"
  when: always

deploy:
  tags:
    - docker-shared
  stage: deploy
  needs:
    - lint
    - unit
  script: echo "$CI_JOB_NAME"
  when: manual
